(()=>{
const C={
fi:{
 eyebrow:'Tietosuoja',title:'Tietosuojaseloste',lead:'Raksa toimii ilman käyttäjätiliä. Laskenta tapahtuu laitteella, eikä laskenta-arvoja lähetetä Raksan palvelimelle.',updated:'Päivitetty',factsTitle:'Tietosuojan pääkohdat',facts:[['Ei käyttäjätiliä','Raksa ei vaadi rekisteröitymistä tai kirjautumista.'],['Laskenta laitteella','Mitat ja laskenta-arvot käsitellään paikallisesti.'],['Ei seurantaa','Ei mainoksia, analytiikkaa eikä profilointia.'],['Ei käyttöoikeuksia','Nykyinen sovellus ei pyydä Android-käyttöoikeuksia.']],toc:['Sisältö','Sovellus','Verkkosivusto','Tietojen hallinta','Yhteystiedot ja muutokset'],home:'Etusivu',groups:[
 {id:'application',n:'01',k:'Android-sovellus',t:'Mitä Raksa käsittelee laitteella',cards:[
  ['Käsiteltävät tiedot','Raksa käsittelee käyttäjän syöttämiä mittoja ja laskenta-arvoja sekä sovelluksen asetuksia ja laskinten tilaa. Näihin kuuluvat esimerkiksi kieli, teema, mittayksikkö, desimaalivalinta sekä kolmio- ja mitoituslaskinten paikallisesti tallennettu tila.'],
  ['Käyttötarkoitus','Tietoja käytetään vain laskentojen suorittamiseen, asetusten muistamiseen ja keskeneräisen laskentatilan palauttamiseen käyttäjän omalla laitteella.'],
  ['Paikallinen tallennus','Asetukset ja laskinten tila tallennetaan Androidin sovelluskohtaiseen SharedPreferences-tallennukseen. Raksa ei lähetä näitä tietoja kehittäjälle tai Raksan palvelimelle.'],
  ['Android-varmuuskopiointi','Android voi käyttäjän varmuuskopiointi- ja laitteensiirtoasetusten mukaisesti varmuuskopioida tai siirtää sovelluksen paikallisia tietoja. Käsittelystä vastaa tällöin käyttöjärjestelmän tai Google-tilin varmuuskopiointipalvelu, ei Raksan oma palvelin.'],
  ['Käyttöoikeudet ja verkkoyhteys','Nykyinen Raksa-versio ei määritä Android-manifestissa käyttöoikeuksia. Laskenta ei tarvitse verkkoyhteyttä eikä pääsyä sijaintiin, kameraan, mikrofoniin, yhteystietoihin, puhelutietoihin tai käyttäjän tiedostoihin.'],
  ['Analytiikka ja mainonta','Nykyisessä sovelluksessa ei ole mainoksia, analytiikkaa, käyttäjäprofilointia, Firebasea, Crashlyticsia tai kolmannen osapuolen seurantaa. Sovelluksen tietoja ei myydä.'] ]},
 {id:'website',n:'02',k:'Verkkosivusto',t:'Mitä rikalo.fi käsittelee',cards:[
  ['Kieli- ja teemavalinnat','Sivusto tallentaa selaimen paikalliseen tallennustilaan valitun kielen ja teeman. Valinnat jäävät selaimeen, eikä sivuston oma koodi lähetä niitä Raksalle.'],
  ['Tekniset lokit','Sivuston hosting- ja verkkopalveluntarjoajat voivat käsitellä esimerkiksi IP-osoitetta, selaintyyppiä, pyynnön ajankohtaa ja pyydettyä osoitetta sivun toimittamista, tietoturvaa ja väärinkäytösten estämistä varten.'],
  ['Evästeet ja seuranta','Raksan sivusto ei käytä omaa analytiikkaa, mainontaa tai seurantapikseleitä. Nykyinen toteutus ei tarvitse evästeitä kieli- ja teemavalintojen tallentamiseen.'] ]},
 {id:'control',n:'03',k:'Tietojen hallinta',t:'Säilytys, poistaminen ja käyttäjän valinnat',cards:[
  ['Sovellustietojen poistaminen','Paikalliset tiedot säilyvät, kunnes käyttäjä tyhjentää Raksan tallennustilan Androidin sovellusasetuksista tai poistaa sovelluksen. Mahdollisia Android-varmuuskopioita hallitaan laitteen ja Google-tilin asetuksissa.'],
  ['Sivustotietojen poistaminen','Kieli- ja teemavalinnat voi poistaa selaimen sivustotietojen tai paikallisen tallennustilan asetuksista.'],
  ['Ei käyttäjäkohtaista palvelinrekisteriä','Raksalla ei ole käyttäjätiliä eikä Raksan palvelimelle tallennettua käyttäjäkohtaista sovellusdataa. Siksi erillistä tilinpoistopyyntöä ei nykyisessä toteutuksessa tarvita.'] ]},
 {id:'contact',n:'04',k:'Vastuut ja muutokset',t:'Rekisterinpitäjä, yhteydenotot ja päivitykset',cards:[
  ['Rekisterinpitäjä ja yhteystiedot','Raksa-sovelluksen kehittäjä ja tietosuojasta vastaava taho on Risto Lohi. Tietosuojaa koskevat yhteydenotot: <a href="mailto:Risto.rikalo@gmail.com">Risto.rikalo@gmail.com</a>.'],
  ['Lapset','Raksa on yleiskäyttöinen rakentamisen laskenta- ja mitoitustyökalu. Sovellus ei pyydä ikää eikä tietoisesti kerää lasten tai muiden käyttäjien henkilötietoja.'],
  ['Tietoturva','Tietojen käsittely on minimoitu sovelluksen toiminnan edellyttämään paikalliseen tallennukseen. Käyttäjän kannattaa suojata laite näytön lukituksella ja pitää Android sekä sovellukset ajan tasalla.'],
  ['Selosteen muutokset','Tätä selostetta ja Google Playn Data safety -tietoja päivitetään ennen sellaisen version julkaisemista, joka muuttaa tietojen käsittelyä. Uusin seloste julkaistaan aina tällä sivulla.','note'] ]}
]},
en:{
 eyebrow:'Privacy',title:'Privacy notice',lead:'Raksa works without a user account. Calculations take place on the device, and calculation values are not sent to a Raksa server.',updated:'Updated',factsTitle:'Privacy highlights',facts:[['No user account','Raksa requires no registration or sign-in.'],['On-device calculations','Measurements and calculation values are processed locally.'],['No tracking','No advertising, analytics, or profiling.'],['No permissions','The current app requests no Android permissions.']],toc:['Contents','Application','Website','Managing data','Contact and changes'],home:'Home',groups:[
 {id:'application',n:'01',k:'Android application',t:'What Raksa handles on the device',cards:[['Data handled','Raksa handles measurements and calculation values entered by the user, along with app preferences and calculator state. This includes language, theme, measurement unit, decimal selection, and locally saved triangle and dimensioning calculator state.'],['Purpose','The information is used only to perform calculations, remember preferences, and restore unfinished calculator state on the user’s own device.'],['Local storage','Preferences and calculator state are stored in Android app-specific SharedPreferences storage. Raksa does not send this information to the developer or to a Raksa server.'],['Android backup','Depending on the user’s backup and device-transfer settings, Android may back up or transfer local app data. In that case processing is performed by the operating system or Google Account backup service, not by a Raksa server.'],['Permissions and network access','The current Raksa version declares no permissions in its Android manifest. Calculations require no network access and no access to location, camera, microphone, contacts, call information, or user files.'],['Analytics and advertising','The current app contains no advertising, analytics, profiling, Firebase, Crashlytics, or third-party tracking. App data is not sold.']]},
 {id:'website',n:'02',k:'Website',t:'What rikalo.fi handles',cards:[['Language and theme choices','The site stores the selected language and theme in browser local storage. The choices remain in the browser, and the site’s own code does not send them to Raksa.'],['Technical logs','Hosting and network providers may process information such as IP address, browser type, request time, and requested address to deliver and secure the site and prevent abuse.'],['Cookies and tracking','The Raksa site uses no first-party analytics, advertising, or tracking pixels. The current implementation does not need cookies to store language and theme choices.']]},
 {id:'control',n:'03',k:'Managing data',t:'Retention, deletion, and user choices',cards:[['Deleting application data','Local information remains until the user clears Raksa storage in Android app settings or uninstalls the app. Any Android backups are managed in device and Google Account settings.'],['Deleting website data','Language and theme choices can be removed through browser site-data or local-storage settings.'],['No user-specific server register','Raksa has no user account and stores no user-specific application data on a Raksa server. A separate account-deletion request is therefore not needed in the current implementation.']]},
 {id:'contact',n:'04',k:'Responsibilities and changes',t:'Controller, contact, and updates',cards:[['Controller and contact','The Raksa developer and party responsible for privacy is Risto Lohi. Privacy enquiries: <a href="mailto:Risto.rikalo@gmail.com">Risto.rikalo@gmail.com</a>.'],['Children','Raksa is a general-purpose construction calculation and dimensioning tool. It does not request age and does not knowingly collect personal data from children or other users.'],['Security','Data handling is minimized to local storage needed for app operation. Users should protect the device with a screen lock and keep Android and installed apps up to date.'],['Changes to this notice','This notice and Google Play Data safety information will be updated before releasing a version that changes data handling. The latest notice will always be published on this page.','note']]}
]}}
function set(id,text){const e=document.getElementById(id);if(e)e.textContent=text}
function render(){const l=document.documentElement.lang==='en'?'en':'fi',d=C[l];set('privacy-eyebrow',d.eyebrow);set('privacy-title',d.title);set('privacy-lead',d.lead);set('updated-label',d.updated);set('facts-title',d.factsTitle);['account','device','tracking','permissions'].forEach((x,i)=>{set(`fact-${x}-title`,d.facts[i][0]);set(`fact-${x}-text`,d.facts[i][1])});['toc-title','toc-app','toc-web','toc-control','toc-contact'].forEach((x,i)=>set(x,d.toc[i]));set('footer-home',d.home);document.title=`${d.title} | Raksa`;document.getElementById('privacy-content').innerHTML=d.groups.map(g=>`<section class="policy-group" id="${g.id}"><div class="policy-group-head"><p class="eyebrow">${g.n} · ${g.k}</p><h2>${g.t}</h2></div>${g.cards.map(c=>`<article class="policy-card${c[2]==='note'?' policy-note':''}"><h3>${c[0]}</h3><p>${c[1]}</p></article>`).join('')}</section>`).join('')}
new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});render();
})();
